### ISSUE TITLE
On ios shows white screen for sometime and then image is loaded

### ISSUE THREAD

**Issue by iparshantnagpal** [TaumuLu/react-native-dynamic-splash#2]

**Comment by TaumuLu** [comment]
@ParshantAroras Sorry, forgot to reply, the current code is no longer maintained, I am planning to refactor this project.

**Comment by bhaskardabhi-oviyum** [comment]
@ParshantAroras I think it will happen the first time only when you install the app and open it. is it? If so then you can add default splash screen in iOS. 

For that, you will have to add an asset with the name "Splash". That worked for me
