### ISSUE TITLE
How to use ? 

### ISSUE THREAD

**Issue by liganghui** [TaumuLu/react-native-dynamic-splash#4]
EN :
  The documentation looks like Android code, I don't know how to use it in react-native. 
please tell me .

CN 
 大兄弟啊  , 这怎么用啊 , 看起来像安卓代码啊 ,  这功能我找了三天了 , 百度 , 谷歌 , Stackoverflow 我都看了 . 今天翻了几十页 github 库  ,  终于发现了你  . 请告诉我怎么用 , 我不怕麻烦 .

**Comment by liganghui** [comment]
我好像看明白了,  谢谢大兄弟 , 爱你哦 .

**Comment by liganghui** [comment]
How can I change the default image displayed for the first time?  
如果更改第一次打开时的默认图片 ?

**Comment by liganghui** [comment]
I solved it .
SplashScreen( https://github.com/crazycodeboy/react-native-splash-screen)
``` javascript
package com.xxxxxxxxx;
import android.os.Bundle;
import android.content.SharedPreferences;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import org.devio.rn.splashscreen.SplashScreen; 
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import com.taumu.rnDynamicSplash.DynamicSplash;
import com.taumu.rnDynamicSplash.utils.Config;
public class MainActivity extends ReactActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SharedPreferences setting = getSharedPreferences("FirstLoad", 0);
        Boolean user_first = setting.getBoolean("FIRST", true);
          if (user_first) {
              setting.edit().putBoolean("FIRST", false).commit();
              Config splashConfig = new Config(); 
              splashConfig.setImageUrl("https://cn.bing.com/ImageResolution.aspx?w=1080&h=1920");
              splashConfig.setAutoHide(true);
              splashConfig.setAutoHideTime(0);
              new DynamicSplash(this, splashConfig);
              SplashScreen.show(this);
         } else {
            Config splashConfig = new Config(); 
            splashConfig.setImageUrl("https://cn.bing.com/ImageResolution.aspx?w=1080&h=1920");
            splashConfig.setDynamicShow(true);
            splashConfig.setAutoHideTime(3200);
            splashConfig.setAutoHide(true);
            new DynamicSplash(this, splashConfig);
         }
        super.onCreate(savedInstanceState);
    }
```

**Comment by TaumuLu** [comment]
初始默认的图片你可以设置下，通过调用splashConfig.setLayoutResId传入layoutResID，默认的是R.layout.splash_dynamic我这里预置的，同理主题也可以通过setThemeResId设置，看readme

**Comment by liganghui** [comment]
> 初始默认的图片你可以设置下，通过调用splashConfig.setLayoutResId传入layoutResID，默认的是R.layout.splash_dynamic我这里预置的，同理主题也可以通过setThemeResId设置，看readme

呃 ，我没有Android开发经验 ，你说的我看不懂 。我已经通过结合react-native-splash-screen的方式 ， 通过判断是否初次加载应用 ，已经解决了这个问题，你可以选择关闭它。

**Comment by VikasReactNative** [comment]
> I solved it . SplashScreen( https://github.com/crazycodeboy/react-native-splash-screen)
> 
> ```js
> package com.xxxxxxxxx;
> import android.os.Bundle;
> import android.content.SharedPreferences;
> import com.facebook.react.ReactActivity;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import org.devio.rn.splashscreen.SplashScreen; 
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> import com.taumu.rnDynamicSplash.DynamicSplash;
> import com.taumu.rnDynamicSplash.utils.Config;
> public class MainActivity extends ReactActivity {
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         SharedPreferences setting = getSharedPreferences("FirstLoad", 0);
>         Boolean user_first = setting.getBoolean("FIRST", true);
>           if (user_first) {
>               setting.edit().putBoolean("FIRST", false).commit();
>               Config splashConfig = new Config(); 
>               splashConfig.setImageUrl("https://cn.bing.com/ImageResolution.aspx?w=1080&h=1920");
>               splashConfig.setAutoHide(true);
>               splashConfig.setAutoHideTime(0);
>               new DynamicSplash(this, splashConfig);
>               SplashScreen.show(this);
>          } else {
>             Config splashConfig = new Config(); 
>             splashConfig.setImageUrl("https://cn.bing.com/ImageResolution.aspx?w=1080&h=1920");
>             splashConfig.setDynamicShow(true);
>             splashConfig.setAutoHideTime(3200);
>             splashConfig.setAutoHide(true);
>             new DynamicSplash(this, splashConfig);
>          }
>         super.onCreate(savedInstanceState);
>     }
> ```

thanks for this help
