### ISSUE TITLE
React-native 0.59+ Android build failed

### ISSUE THREAD

**Issue by liganghui** [TaumuLu/react-native-dynamic-splash#5]
need to upgrade the android build version
Similar reference:
https://github.com/Kishanjvaghela/react-native-cardview/blob/master/android/build.gradle

 CN :  需要升级安卓构建版本
你可以参考 其他库的解决方式 :
https://github.com/Kishanjvaghela/react-native-cardview/blob/master/android/build.gradle

 warning  Code :
```javascript
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

**Comment by TaumuLu** [comment]
> need to upgrade the android build version
> Similar reference:
> https://github.com/Kishanjvaghela/react-native-cardview/blob/master/android/build.gradle
> 
> CN : 需要升级安卓构建版本
> 你可以参考 其他库的解决方式 :
> https://github.com/Kishanjvaghela/react-native-cardview/blob/master/android/build.gradle
> 
> warning Code :
> 
> ```js
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> WARNING: The specified Android SDK Build Tools version (23.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0.
> Android SDK Build Tools 28.0.3 will be used.
> To suppress this warning, remove "buildToolsVersion '23.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> ```

+ react-native-dynamic-splash@1.1.2
