### ISSUE TITLE
 js incoming url as image download link 啥时候可以实现？

### ISSUE THREAD

**Issue by qiruiqq3** [TaumuLu/react-native-dynamic-splash#6]
请问作者 js incoming url as image download link这个功能啥时候可以实现？谢谢

**Comment by TaumuLu** [comment]
> 请问作者 js incoming url as image download link这个功能啥时候可以实现？谢谢

周末我做下吧

**Comment by qiruiqq3** [comment]
作者辛苦了 ！！！
昨天在android版本下，改了一下，RN端通过NativeModules来调用，可以了 
   @ReactMethod
    public void downloadSplash(String logoUrl) {
        mConfig.setImageUrl(logoUrl);
        mDynamicSplash.downloadSplash(getCurrentActivity());
    }
测试发现一个小问题，就是点击app图标，然后需要延迟0.5s才能打开app显示启动页，而不是直接就打开，感觉上会卡顿一些

今天开始调试IOS的

**Comment by TaumuLu** [comment]
延迟的问题要给Activity设置一个默认启动图的theme

**Comment by qiruiqq3** [comment]
> 延迟的问题要给Activity设置一个默认启动图的theme

好的，谢谢

**Comment by qiruiqq3** [comment]
![image](https://user-images.githubusercontent.com/3963155/62036779-0ccff480-b225-11e9-83db-705bd9e35b6f.png)
IOS也一样，现在可以了，不知道这样写，有没有问题。
直接取_config为null，实例化了一下后可以了

**Comment by qiruiqq3** [comment]
> 延迟的问题要给Activity设置一个默认启动图的theme

这个问题请作者指点一下，谢谢！
尝试了一些解决方案，还是有延迟

**Comment by TaumuLu** [comment]
> ![image](https://user-images.githubusercontent.com/3963155/62036779-0ccff480-b225-11e9-83db-705bd9e35b6f.png)
> IOS也一样，现在可以了，不知道这样写，有没有问题。
> 直接取_config为null，实例化了一下后可以了

也是可以的，但application里传的config应该就会没用了吧

**Comment by TaumuLu** [comment]
> > 延迟的问题要给Activity设置一个默认启动图的theme
> 
> 这个问题请作者指点一下，谢谢！
> 尝试了一些解决方案，还是有延迟

这个思路是先加一个启动图，然后在启动图后onCreate里再展示下载的动态图
启动图参考[这里](https://blog.csdn.net/yanzhenjie1003/article/details/52201896)的秒开方案

**Comment by qiruiqq3** [comment]
> > > 延迟的问题要给Activity设置一个默认启动图的theme
> > 
> > 
> > 这个问题请作者指点一下，谢谢！
> > 尝试了一些解决方案，还是有延迟
> 
> 这个思路是先加一个启动图，然后在启动图后onCreate里再展示下载的动态图
> 启动图参考[这里](https://blog.csdn.net/yanzhenjie1003/article/details/52201896)的秒开方案

多谢，秒开已经实现。

**Comment by qiruiqq3** [comment]
android下，模拟器没有问题，所有功能都正常。
但是发布后，登录后就报错了
android.view.WindowLeaked
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:403)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:330)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:106)
        at android.app.Dialog.show(Dialog.java:346)
        at com.taumu.rnDynamicSplash.DynamicSplash$1.run(DynamicSplash.java:51)
        at android.app.Activity.runOnUiThread(Activity.java:5644)
        at com.taumu.rnDynamicSplash.DynamicSplash.<init>(DynamicSplash.java:35)

**Comment by qiruiqq3** [comment]
谢谢 作者，已经实现了。
